RAIDMED-PROJECT-ORG/RAIMED2

raimed2Back/src/test/java/fr/imt/raimed2/action/model/ActionClosedQuestionTest.java
raimed2Back/src/test/java/fr/imt/raimed2/action/model/ActionOpenedQuestionTest.java
raimed2Back/src/test/java/fr/imt/raimed2/action/model/ActionSpontaneousPatientSpeechTest.java
raimed2Back/src/test/java/fr/imt/raimed2/action/model/ActionTest.java
raimed2Back/src/test/java/fr/imt/raimed2/action/service/ActionServiceTest.java
raimed2Back/src/test/java/fr/imt/raimed2/diagnostic/service/DiagnosticServiceTest.java
raimed2Back/src/test/java/fr/imt/raimed2/integration/authentication/AuthenticationIntegrationTest.java
raimed2Back/src/test/java/fr/imt/raimed2/question/model/QuestionTest.java
raimed2Back/src/test/java/fr/imt/raimed2/question/service/QuestionServiceTest.java
raimed2Back/src/test/java/fr/imt/raimed2/user/model/UserTest.java
raimed2Back/src/test/java/fr/imt/raimed2/user/service/UserServiceTest.java

- Test service et modèle action
- Test service diagnostic
- Test service et modèle user
- Test service et modèle question
- Test integration authentification

✅ Unit testing for Spring Services

---

raimed2Front/src/components/actionButton/ActionButton.vue
raimed2Front/src/components/diagnosticActions/DiagnosticActions.vue

Add a new custom action button to be more generic.
- Changement 1
- Changement 2
- ...

KAN-20: Create custom action button

---

raimed2Front/src/views/HomeView.vue

Kan 10 faire la vue du front accueil

---

raimed2Front/src/components/actionButton/ActionButton.vue
raimed2Front/src/components/diagnosticActions/DiagnosticActions.vue
raimed2Front/src/router/index.ts
raimed2Front/src/views/NewPatientView.vue

Create view "New patient".
- Added a view
- Routed the view
- Refactored custom button

KAN-16: Create view "New patient"

---

raimed2Front/src/components/actionButton/ActionButton.vue
raimed2Front/src/components/drawerMenu/DrawerMenu.vue
raimed2Front/src/components/modalDiagnosticValidation/ModalDiagnosticValidation.vue
raimed2Front/src/layouts/AuthenticatedViewLayout.vue
raimed2Front/src/router/index.ts
raimed2Front/src/views/teacher/PatientsView.vue
raimed2Front/tailwind.config.js

- Changement 1
- Changement 2
- ...

KAN-13-Faire-la-vue-Liste-des-patients

---

raimed2Front/.eslintrc.cjs
raimed2Front/src/router/index.ts
raimed2Front/src/views/HomeView.vue
raimed2Front/src/views/NewPatientView.vue
raimed2Front/src/views/teacher/PatientsView.vue

Route patient list and patient creation views.
- Changement 1
- Changement 2
- ...

KAN-11: Route patient list and patient creation views

---

.github/workflows/spring-boot.yml
.gitignore

Offload l'execution de tests containers via le service cloud Test Containers.
- Connexion au service et config du secret

:ci: 💚Add test containers service to offload the CI

---

raimed2Front/src/components/actionButton/ActionButton.vue
raimed2Front/src/components/diagnosticActions/DiagnosticActions.vue
raimed2Front/src/components/dropdownButton/DropdownButton.vue
raimed2Front/src/components/iconLabel/IconLabel.vue
raimed2Front/src/components/modal/characteristicModal/CharacteristicModal.vue
raimed2Front/src/views/NewPatientView.vue

Add characteristics modal and plug it.
- Changement 1
- Changement 2
- ...

KAN-19: Add characteristics modal and plug it

---

raimed2Back/src/main/java/fr/imt/raimed2/virtualPatient/dto/VirtualPatientEntityDtoMapper.java
raimed2Back/src/main/java/fr/imt/raimed2/virtualPatient/dto/response/VirtualPatientDto.java
raimed2Front/src/models/virtual-patient/virtualPatient.model.ts
raimed2Front/src/stores/patient.store.ts
raimed2Front/src/views/teacher/PatientsView.vue

- Chargement automatique des patients dans la liste des patients
- AJout redirection bouton homepage to liste des patients

Kan 23 alimenter la liste des patients dynamiquement

---

raimed2Front/src/components/multipleSelector/MultipleSelector.vue

Create a new component : MultipleSelector
- Changement 1
- Changement 2
- ...

KAN-31: Add multiple selector component

---

raimed2Back/src/main/java/fr/imt/raimed2/action/model/Action.java
raimed2Back/src/main/java/fr/imt/raimed2/virtualPatient/controller/VirtualPatientController.java
raimed2Back/src/main/java/fr/imt/raimed2/virtualPatient/model/VirtualPatient.java
raimed2Back/src/main/java/fr/imt/raimed2/virtualPatient/service/VirtualPatientService.java
raimed2Front/src/stores/patient.store.ts
raimed2Front/src/views/teacher/PatientsView.vue

- Suppr d'un patient (et associés en cascade)

Kan 14 action suppression patient

---

raimed2Back/src/main/java/fr/imt/raimed2/action/model/Action.java
raimed2Back/src/main/java/fr/imt/raimed2/action/model/ActionClosedQuestion.java
raimed2Back/src/main/java/fr/imt/raimed2/action/model/ActionOpenedQuestion.java
raimed2Back/src/main/java/fr/imt/raimed2/diagnostic/model/Diagnostic.java
raimed2Back/src/main/java/fr/imt/raimed2/diagnostic/model/Event.java
raimed2Back/src/main/java/fr/imt/raimed2/diagnostic/model/Interpretation.java
raimed2Back/src/main/java/fr/imt/raimed2/diagnostic/model/Reasoning.java
raimed2Back/src/main/java/fr/imt/raimed2/user/model/User.java
raimed2Back/src/main/java/fr/imt/raimed2/virtualPatient/model/VirtualPatient.java

- Changement 1
- Changement 2
- ...

fix: bug patient fonctionne

---

raimed2Front/src/components/modal/examModal/ExamModal.vue
raimed2Front/src/components/modal/examenModal/ExamenModal.vue
raimed2Front/src/components/modal/genericModal/GenericModal.vue
raimed2Front/src/components/modal/questionModal/QuestionModal.vue
raimed2Front/src/models/virtual-patient/typeAction.enum.ts
raimed2Front/src/views/NewPatientView.vue

PR pour corriger le cas où y'a eu des modifications non sauvegardées qui étaient quand même sauvegardées. Puis ajout d'un garde fou.
- Changement 1
- Changement 2
- ...

KAN-40: Add a modal to confirm we want to go back

---

raimed2Back/src/main/java/fr/imt/raimed2/question/controller/QuestionController.java
raimed2Back/src/main/java/fr/imt/raimed2/question/repository/QuestionRepository.java
raimed2Back/src/main/java/fr/imt/raimed2/question/service/QuestionService.java
raimed2Front/src/stores/questions.store.ts

- Changement 1
- Changement 2
- ...

Kan 44 nouvelles routes pour recuperer les questions

---

raimed2Front/src/assets/common.css
raimed2Front/src/assets/main.css
raimed2Front/src/components/modal/characteristicModal/CharacteristicModal.vue
raimed2Front/src/components/modal/genericModal/GenericModal.vue
raimed2Front/src/components/modal/listenModal/ListenForm.vue
raimed2Front/src/components/modal/listenModal/ListenList.vue
raimed2Front/src/components/modal/listenModal/ListenListModal.vue
raimed2Front/src/components/modal/listenModal/ListenListModalHeader.vue
raimed2Front/src/components/modal/listenModal/ListenModal.vue
raimed2Front/src/components/modal/listenModal/ListenRow.vue
raimed2Front/src/components/modal/questionModal/QuestionForm.vue
raimed2Front/src/components/modal/questionModal/QuestionListModal.vue
raimed2Front/src/components/modal/questionModal/QuestionListModalHeader.vue
raimed2Front/src/components/modal/questionModal/QuestionModal.vue
raimed2Front/src/models/listen/listen.model.ts
raimed2Front/src/models/new-patient/characteristics.model.ts
raimed2Front/src/models/new-patient/newPatient.model.ts
raimed2Front/src/models/question/questionFilter.enum.ts
raimed2Front/src/models/virtual-patient/gender.enum.ts
raimed2Front/src/views/NewPatientView.vue

- Changement 1
- Changement 2
- ...

KAN-43-Modal-Écouter

---

raimed2Front/src/components/categoryButton/CategoryButton.vue
raimed2Front/src/components/progressBar/ProgressBar.vue
raimed2Front/src/views/NewPatientView.vue
raimed2Front/src/views/teacher/PatientsView.vue

- Changement 1
- Changement 2
- ...

KAN-45: UX improvements of new patient form

---

raimed2Back/src/main/java/fr/imt/raimed2/action/model/Action.java
raimed2Back/src/main/java/fr/imt/raimed2/action/service/ActionService.java
raimed2Back/src/main/java/fr/imt/raimed2/question/dto/xml/QuestionLinkedDTO.java
raimed2Back/src/main/java/fr/imt/raimed2/question/repository/QuestionRepository.java
raimed2Back/src/main/java/fr/imt/raimed2/question/service/QuestionService.java
raimed2Back/src/main/java/fr/imt/raimed2/virtualPatient/dto/response/VirtualPatientListDto.java
raimed2Back/src/main/java/fr/imt/raimed2/virtualPatient/dto/xml/VirtualPatientDTO.java
raimed2Back/src/main/java/fr/imt/raimed2/virtualPatient/model/VirtualPatient.java
raimed2Back/src/main/java/fr/imt/raimed2/virtualPatient/service/VirtualPatientService.java
raimed2Front/package-lock.json
raimed2Front/package.json
raimed2Front/src/models/virtual-patient/action.model.ts
raimed2Front/src/models/virtual-patient/virtualPatient.model.ts
raimed2Front/src/stores/patient.store.ts
raimed2Front/src/stores/questions.store.ts
raimed2Front/src/views/NewPatientView.vue
raimed2Front/src/views/teacher/PatientsView.vue

- Changement 1
- Changement 2
- ...

feat: sauvegarde patient avec characteristiques et questions

---

raimed2Front/src/assets/common.css
raimed2Front/src/components/categoryButton/CategoryButton.vue
raimed2Front/src/components/modal/listenModal/ListenForm.vue
raimed2Front/src/components/modal/listenModal/ListenList.vue
raimed2Front/src/components/modal/listenModal/ListenRow.vue
raimed2Front/src/components/modal/questionModal/QuestionForm.vue
raimed2Front/src/components/modal/questionModal/QuestionList.vue
raimed2Front/src/components/modal/questionModal/QuestionRow.vue
raimed2Front/src/components/multipleSelector/MultipleSelector.vue
raimed2Front/src/components/singleValueSelector/SingleValueSelector.vue
raimed2Front/src/models/listen/listen.model.ts
raimed2Front/src/models/question/question.model.ts

Ajout des éléments primaires aux actions questions + écouter
- Changement 1
- Changement 2
- ...

KAN-47: Add primary elements to "listen" and "question" categories

---

raimed2Front/src/components/categoryButton/CategoryButton.vue
raimed2Front/src/components/modal/examModal/ExamModal.vue
raimed2Front/src/components/modal/listenModal/ListenModal.vue
raimed2Front/src/components/modal/precisionModal/PrecisionForm.vue
raimed2Front/src/components/modal/precisionModal/PrecisionList.vue
raimed2Front/src/components/modal/precisionModal/PrecisionModal.vue
raimed2Front/src/components/modal/precisionModal/PrecisionRow.vue
raimed2Front/src/components/modal/questionModal/QuestionModal.vue
raimed2Front/src/components/singleValueSelector/SingleValueSelector.vue
raimed2Front/src/models/new-patient/newPatient.model.ts
raimed2Front/src/models/question/precision.model.ts
raimed2Front/src/views/NewPatientView.vue

Add the symptom precision modal and plug it to the form.
- Changement 1
- Changement 2
- ...

KAN-51: Add symptom precision modal

---

raimed2Back/src/main/java/fr/imt/raimed2/action/repository/ActionPrescriptionRepository.java
raimed2Back/src/main/java/fr/imt/raimed2/action/repository/ActionRepository.java
raimed2Back/src/main/java/fr/imt/raimed2/action/service/ActionService.java
raimed2Back/src/main/java/fr/imt/raimed2/diagnostic/controller/DiagnosticController.java
raimed2Back/src/main/java/fr/imt/raimed2/diagnostic/service/DiagnosticService.java
raimed2Front/src/components/diagnosticActions/DiagnosticActions.vue
raimed2Front/src/components/diagnosticActions/PrescriptionPanel.vue
raimed2Front/src/models/virtual-patient/typeAction.enum.ts
raimed2Front/src/stores/diagnostic.store.ts
raimed2Front/src/stores/patient.store.ts
raimed2Front/src/views/DiagnosticView.vue
raimed2Front/src/views/teacher/NewPatientView.vue

Add prescription actions in diagnostic view with a new backend query
- Changement 1
- Changement 2
- ...
https://github.com/user-attachments/assets/4b0f55ae-0605-4bce-95c9-20f0519ac0c0

KAN-48: Add prescription actions in diagnostic view

---

raimed2Back/src/main/java/fr/imt/raimed2/action/dto/xml/ActionClosedQuestionDTO.java
raimed2Back/src/main/java/fr/imt/raimed2/question/model/Question.java
raimed2Back/src/main/java/fr/imt/raimed2/virtualPatient/controller/VirtualPatientController.java
raimed2Back/src/main/java/fr/imt/raimed2/virtualPatient/dto/xml/VirtualPatientDTO.java
raimed2Back/src/main/java/fr/imt/raimed2/virtualPatient/repository/VirtualPatientRepository.java
raimed2Front/src/stores/patient.store.ts

- Ajout de la méthode en front pour ajouter le speech du patient

Kan 50 sauvegarder action speech patient

---

raimed2Back/src/main/java/fr/imt/raimed2/action/repository/ActionRepository.java
raimed2Back/src/main/java/fr/imt/raimed2/prescription/model/Prescription.java
raimed2Back/src/main/java/fr/imt/raimed2/virtualPatient/service/VirtualPatientService.java
raimed2Front/src/stores/patient.store.ts
raimed2Front/src/views/teacher/EditPatientView.vue
raimed2Front/src/views/teacher/NewPatientView.vue
raimed2Front/src/views/teacher/PatientsView.vue

- Changement 1
- Changement 2
- ...

Kan 56 fix edition

---

raimed2Back/src/main/java/fr/imt/raimed2/action/dto/xml/ActionAuscultationDTO.java
raimed2Back/src/main/java/fr/imt/raimed2/action/dto/xml/ActionDTO.java
raimed2Back/src/main/java/fr/imt/raimed2/action/dto/xml/ActionInspectionDTO.java
raimed2Back/src/main/java/fr/imt/raimed2/action/dto/xml/ActionPalpationDTO.java
raimed2Back/src/main/java/fr/imt/raimed2/action/dto/xml/ActionPercussionDTO.java
raimed2Back/src/main/java/fr/imt/raimed2/action/model/ActionAuscultation.java
raimed2Back/src/main/java/fr/imt/raimed2/action/model/ActionExamen.java
raimed2Back/src/main/java/fr/imt/raimed2/action/model/ActionInspection.java
raimed2Back/src/main/java/fr/imt/raimed2/action/model/ActionPalpation.java
raimed2Back/src/main/java/fr/imt/raimed2/action/model/ActionPercussion.java
raimed2Back/src/main/java/fr/imt/raimed2/action/service/ActionService.java
raimed2Back/src/main/java/fr/imt/raimed2/virtualPatient/service/VirtualPatientService.java
raimed2Front/src/stores/patient.store.ts

Je sais pas si ca regle l'édition mais on peut distinguer les eenregistrements en regardant le type via primaryElement quand on stock l'action
- Changement 1
- Changement 2
- ...

Fix temporaire pour sauvegarde

---

raimed2Back/src/main/java/fr/imt/raimed2/action/model/ActionExamen.java
raimed2Back/src/main/java/fr/imt/raimed2/action/repository/ActionPrecisionRepository.java
raimed2Back/src/main/java/fr/imt/raimed2/action/service/ActionService.java
raimed2Back/src/main/java/fr/imt/raimed2/diagnostic/controller/DiagnosticController.java
raimed2Back/src/main/java/fr/imt/raimed2/diagnostic/service/DiagnosticService.java
raimed2Front/src/components/diagnosticActions/PrecisionPanel.vue
raimed2Front/src/composable/useApiToLocalPatientMapper.ts
raimed2Front/src/models/virtual-patient/typeAction.enum.ts
raimed2Front/src/stores/diagnostic.store.ts
raimed2Front/src/views/DiagnosticView.vue

- Changement 1
- Changement 2
- ...

KAN-58: Plug precision & fix EXAMEN type

---

raimed2Back/src/main/java/fr/imt/raimed2/action/model/ActionExamen.java
raimed2Back/src/main/java/fr/imt/raimed2/action/repository/ActionPrecisionRepository.java
raimed2Back/src/main/java/fr/imt/raimed2/action/repository/ActionRepository.java
raimed2Back/src/main/java/fr/imt/raimed2/action/service/ActionService.java
raimed2Back/src/main/java/fr/imt/raimed2/diagnostic/controller/DiagnosticController.java
raimed2Back/src/main/java/fr/imt/raimed2/diagnostic/service/DiagnosticService.java
raimed2Back/src/main/java/fr/imt/raimed2/diagnostic/service/ReasoningService.java
raimed2Front/src/components/diagnosticActions/ExamPanel.vue
raimed2Front/src/components/diagnosticActions/PrecisionPanel.vue
raimed2Front/src/components/diagnosticActions/PrescriptionPanel.vue
raimed2Front/src/components/primaryElementList/PrimaryElementList.vue
raimed2Front/src/composable/useApiToLocalPatientMapper.ts
raimed2Front/src/models/diagnostic/exam.model.ts
raimed2Front/src/models/exam/exam.model.ts
raimed2Front/src/models/exam/examType.enum.ts
raimed2Front/src/models/virtual-patient/action.model.ts
raimed2Front/src/models/virtual-patient/typeAction.enum.ts
raimed2Front/src/stores/diagnostic.store.ts
raimed2Front/src/stores/patient.store.ts
raimed2Front/src/views/DiagnosticView.vue

- Changement 1
- Changement 2
- ...

Kan 57 étudiant actions orange

---

raimed2Back/src/main/java/fr/imt/raimed2/question/controller/QuestionController.java
raimed2Back/src/main/java/fr/imt/raimed2/question/dto/request/CreateQuestionDto.java
raimed2Back/src/main/java/fr/imt/raimed2/question/dto/request/UpdateQuestionDto.java
raimed2Front/src/components/modal/questionModal/QuestionListModal.vue
raimed2Front/src/components/modal/questionModal/QuestionListModalHeader.vue
raimed2Front/src/components/modal/questionModal/QuestionRow.vue
raimed2Front/src/components/questionManagement/CreateQuestionForm.vue
raimed2Front/src/stores/questions.store.ts
raimed2Front/src/views/administration/QuestionsView.vue

- Changement 1
- Changement 2
- ...

KAN-60: Import question

---

raimed2Back/src/main/java/fr/imt/raimed2/diagnostic/service/ReasoningService.java
raimed2Back/src/main/java/fr/imt/raimed2/virtualPatient/controller/VirtualPatientController.java
raimed2Back/src/main/java/fr/imt/raimed2/virtualPatient/dto/response/VirtualPatientDto.java
raimed2Back/src/main/java/fr/imt/raimed2/virtualPatient/dto/response/VirtualPatientListDto.java
raimed2Front/src/components/diagnosticActions/DiagnosticActions.vue
raimed2Front/src/components/diagnosticActions/PrecisionPanel.vue
raimed2Front/src/components/hypothesisList/HypothesisList.vue
raimed2Front/src/components/interpretationList/InterpretationList.vue
raimed2Front/src/components/modal/characteristicModal/CharacteristicModal.vue
raimed2Front/src/components/syndromList/SyndromList.vue
raimed2Front/src/composable/useApiToLocalPatientMapper.ts
raimed2Front/src/models/new-patient/newPatient.model.ts
raimed2Front/src/models/virtual-patient/virtualPatient.model.ts
raimed2Front/src/stores/diagnostic.store.ts
raimed2Front/src/stores/patient.store.ts
raimed2Front/src/views/DiagnosticResultView.vue
raimed2Front/src/views/HomeView.vue
raimed2Front/src/views/teacher/NewPatientView.vue
raimed2Front/src/views/teacher/PatientsView.vue

- Changement 1
- Changement 2
- ...

Kan 59 few fixes

---

raimed2Back/src/main/java/fr/imt/raimed2/action/model/Action.java
raimed2Back/src/main/java/fr/imt/raimed2/action/service/ActionService.java
raimed2Back/src/main/resources/db/migration/V0.0.11__make_primary_element_nullable.sql
raimed2Front/src/stores/diagnostic.store.ts
raimed2Front/src/stores/patient.store.ts

- Changement 1
- Changement 2
- ...

fix: empty primary element for listen and closed questions
